- hosts: localhost
  vars_prompt:
    - name: sudo_password
      prompt: "Please enter your sudo password"
    
    - name: kaspersky_key
      prompt: "Please enter your Kaspersky license key"
      private: no
      
  tasks:
    - name: Gather facts about installed packages
      package_facts:
        manager: "auto"
    
    - name: Create software list/set sudo password
      set_fact:
        ansible_become_pass: "{{ sudo_password}}"
    
    - name: Remove old Kaspersky version (if installed)
      become: yes
      package:
        name: kesl*
        state: absent
    
    - name: Remove old installation files (clear /tmp directory)
      file:
        path: "/tmp/{{ item }}"
        state: absent
      with_items:
        - kesl.rpm
        - kesl-gui.rpm
    
    - name: Run kesl install script
      expect:
        command: "{{ playbook_dir }}/kaspersky-installer/kesl_install.sh -i"
        responses:
          ".*sudo.*": "{{ sudo_password }}"
          ".*license.*": "{{ kaspersky_key }}"
          ".*reboot.*": "N"
        timeout: 500
